require('plugins.manager')
require('plugins.config.telescope')
require('plugins.config.rosepine')
require('plugins.config.tabby')
-- require('plugins.config.netrw')
require('plugins.config.nvimtree')
-- require('plugins.config.treesitter')
-- require('plugins.config.lualine')
-- require('plugins.config.catppuccin')
